#!/bin/bash

# Allow importing `awslambdaric` from lambda layer
export PYTHONPATH=$PYTHONPATH:/opt/python/lib

# Allow importing `boto3` from lambda runtime environment
export PYTHONPATH=$PYTHONPATH:/var/runtime

# Bootstrap lambda custom runtime
exec /var/lang/bin/python3.9 /opt/python/bootstrap.py
